pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
github_token: ((github_token)) # [R] Your github token
github_repo: https://github.com/rahul-kj/concourse-vsphere # [R] Pipelines github repo
github_branch: develop
github_username: ((github_username)) # [R] Your github username

iaas_type: vsphere-esxi # azure-hyperv|vsphere-esxi|aws-xen-hvm|openstack-kvm|vcloud-esxi|google-kvm

debug: true

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr))  # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd))  # [R] Ops Manager admin password

product_name: pivotal_single_sign-on_service # Product slug from PivNet
product_identifier: Pivotal_Single_Sign-On_Service # product identifier using OM cli
product_version: ^1\.6\..*$

singleton_jobs_az: ((singleton_jobs_az)) # [R] Place singleton jobs in an AZ
other_azs: ((other_azs)) # [R] Balance other jobs in AZ's
network_name: ((network_name)) # [R] Tile network name

errands_to_disable: ''

concourse_user: ((concourse_user))
concourse_pwd: ((concourse_pwd))
concourse_url: ((concourse_url))
pipeline-name: install-single-signon
team-name: ((team-name))
upgrade-pipeline-name: upgrade-single-signon
