# Token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: <YOUR-PIVNET-TOKEN>

# The token used to download the repos from GitHub for the pipelines
github_token: <YOUR-GITHUB-TOKEN>
github_repo: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
github_branch: master
github_username: # [R] Your github username

gist_url: ((gist_url))

debug: false # Set to true if you want to see all the tasks output. This will also show all the secrets and certs, so think twice

opsman_product_version: ^2\.1\..*$

# Enter vCenter details
vcenter_host: <VCENTER-HOST-OR-IP>
vcenter_usr: <VCENTER-SERVICE-USR> # If user is tied to a domain, then escape the \, example `domain\\user`
vcenter_pwd: <VCENTER-SERVICE-USR-PWD>

# Ops Manager installation meta data
ops_mgr_host: <DESIRED-OPS-MANAGER-FQDN> # FQDN to access Ops Manager, ex: opsmgr.example.com
ops_mgr_usr: <DESIRED-OPS-MANAGER-USR> # Ops Manager admin username
ops_mgr_pwd: <DESIRED-OPS-MANAGER-PWD> # Ops Manager admin password
ops_mgr_ip: <DESIRED-OPS-MANAGER-IP> # Ops Manager Static IP

concourse_username: ((concourse_user))
concourse_passwd: ((concourse_pwd))
concourse_url: ((concourse_url))
team_name: ((team_name))
install_pipeline_name: install-pcf
install_pipeline_state: unpause

reinstall_pipeline_name: reinstall-pcf
reinstall_pipeline_state: pause
