FROM ubuntu:18.04
MAINTAINER rahulkj@gmail.com

RUN apt-get update && apt-get install -y vim curl wget git \
    jq python nano unzip uuid-runtime iputils-ping dnsutils \
    ca-certificates netcat telnet ruby

RUN ruby -v
