# Token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
git_token: ((github_token)) # [R] Your github token
git_url: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
git_branch: master
git_username: ((github_username)) # [R] Your github username

iaas_type: vsphere-esxi # azure-hyperv|vsphere-esxi|aws-xen-hvm|openstack-kvm|vcloud-esxi|google-kvm

debug: false

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr))  # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd))  # [R] Ops Manager admin password

product_name: apm
product_identifier: apm
product_version: ^1\.4\..*$

singleton_jobs_az: ((singleton_jobs_az)) # [R] Place singleton jobs in an AZ
other_azs: ((other_azs)) # [R] Balance other jobs in AZ's
network_name: ((network_name)) # [R] Tile network name

dependency_product_tiles: 'cf'

mysql_roadmin_password: ''
mysql_skip_name_resolve: true
push_apps_elasticsearch_logqueue_instance_count: 1
push_apps_ingestor_instance_count: 1
push_apps_logs_retention_window: 14
push_apps_metrics_retention_window: 14
push_apps_mysql_logqueue_instance_count: 1
push_apps_server_instance_count: 1
elasticsearch_master_instances: 1
elasticsearch_master_instance_type: large
elasticsearch_master_persistent_disk_mb: 10240
elasticsearch_data_instances: 4
elasticsearch_data_instance_type: xlarge
elasticsearch_data_persistent_disk_mb: 102400
redis_instances: 1
redis_instance_type: medium
redis_persistent_disk_mb: 102400

errands_to_disable: # "push-apps,migrate-data-to-1-4,smoke-tests,delete-metrics-1-3-space"
